import { supabase } from './supabase.js';
export type PaperSniperConfig = { enabled: boolean; mode: 'PAPER'; amountUsd: number; maxValuationUsd: number | null; minimumLiquidityUsd: number | null; acceptableLpSafety: Array<'LOCKED' | 'BURNED' | 'UNLOCKED'>; maxDeveloperHoldingPercent: number | null; rejectConfirmedDeveloperSell: boolean; requireSustainedConfirmation: boolean; requireDexPaid: boolean; minimumBoost: number | null; requireVolumeAcceleration: boolean; maxSlippageBps: number; maxSimultaneousPositions: number; cooldownSeconds: number; maximumDailyPaperLossUsd: number | null };
export function assertPaperOnly(config: Pick<PaperSniperConfig, 'mode'>): void { if (config.mode !== 'PAPER') throw new Error('Only PAPER mode is supported; live execution is unavailable.'); }
export async function savePaperSniperConfig(telegramId: string, config: PaperSniperConfig): Promise<void> {
  assertPaperOnly(config);
  const { error } = await supabase.from('user_paper_sniper_configs').upsert({ telegram_id: telegramId, enabled: config.enabled, mode: 'PAPER', amount_usd: config.amountUsd, max_valuation_usd: config.maxValuationUsd, minimum_liquidity_usd: config.minimumLiquidityUsd, acceptable_lp_safety: config.acceptableLpSafety, max_developer_holding_percent: config.maxDeveloperHoldingPercent, reject_confirmed_developer_sell: config.rejectConfirmedDeveloperSell, require_sustained_confirmation: config.requireSustainedConfirmation, require_dex_paid: config.requireDexPaid, minimum_boost: config.minimumBoost, require_volume_acceleration: config.requireVolumeAcceleration, max_slippage_bps: config.maxSlippageBps, max_simultaneous_positions: config.maxSimultaneousPositions, cooldown_seconds: config.cooldownSeconds, maximum_daily_paper_loss_usd: config.maximumDailyPaperLossUsd, updated_at: new Date().toISOString() }, { onConflict: 'telegram_id' });
  if (error) throw error;
}
export function executePaperSniper(): never { throw new Error('Paper sniper execution is intentionally not connected in this phase.'); }
