import test from 'node:test';
import assert from 'node:assert/strict';
import { createPonsLiveLaunchRouter } from '../src/chains/robinhood/ponsLiveLaunchRouter.js';
import { replayPonsLiveLaunch, type PersistedPonsLaunch } from '../src/chains/robinhood/ponsLiveReplay.js';

const token = '0xe0eba1b76b73be7bfa7716b6ca96f724930e2263';
const row: PersistedPonsLaunch = { token_address:token.toUpperCase(),deployer_address:'0xAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',factory_address:'0x7eD598BcEf8bd9Edd8C97A195C6d13f40801EC7e',protocol_version:'v2-current',transaction_hash:`0x${'ab'.repeat(32)}`,block_number:'27027321',block_timestamp:'2026-09-04T00:00:00Z',log_index:3 };
const registry=(tier:string,blocked=false)=>({deployerAddress:row.deployer_address.toLowerCase(),tier,riskTier:blocked?tier:null,confidence:'HIGH',isBlocked:blocked,blockReason:blocked?'blocked evidence':null,blockedAt:null,totalLaunches:20,usableOutcomes:10,winners100k:5,winners500k:2,winners1m:1,winners5m:0,winners10m:0,bestVerifiedPeakMarketCap:1_500_000,bestTokenAddress:'0xold',hitRate100k:.5,hitRate1m:.1,recent5Hits100k:2,recent5Hits1m:1,severeCrashCount:0,severeCrashRate:0,catastrophicCrashCount:0,catastrophicCrashRate:0,firstLaunchAt:null,latestLaunchAt:null,lastSuccessfulTokenAddress:'0xold',lastSuccessfulPeakMarketCap:1_500_000}) as never;
const market=(price=1,buys=10,sells=5)=>({chain:'robinhood',tokenAddress:token,symbol:'R',name:'Replay',priceUsd:price,marketCapUsd:100_000*price,liquidityUsd:50_000,volume5mUsd:10_000,buys5m:buys,sells5m:sells,pairAddress:'0xpair',timestamp:Date.now(),source:'DEXSCREENER'}) as const;
const config={liveIntelligenceEnabled:true,provenDeveloperAlertsEnabled:true,shadowBuyEnabled:true,confirmationSeconds:0,successfulDeveloperMinPeakMarketCap:300_000};

test('GEM replay reconstructs the persisted event and reaches the proven-dev route',async()=>{const logs:string[]=[];const snapshots=[market(),market(1.01,20,8)];const route=createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>registry('GEM'),loadMarket:async()=>snapshots.shift()!,emitAlert:async()=>{},emitDecision:async()=>{},sleep:async()=>{},log:()=>{}});const result=await replayPonsLiveLaunch(token,{loadExactLaunch:async exact=>{assert.equal(exact,token);return row}},route,line=>logs.push(line));assert.equal(result.status,'PROVEN_PROCESSED');assert.equal(result.decision?.action,'BUY');assert.ok(logs.includes('[PonsLiveReplay] tier=GEM'));assert.ok(logs.includes('[PonsLiveReplay] decision=SHADOW_BUY'))});

test('SCAMMER and SPAM replay stop before expensive enrichment',async()=>{for(const tier of ['SCAMMER','SPAM_LAUNCHER']){let markets=0,sleeps=0,alerts=0;const route=createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>registry(tier,true),loadMarket:async()=>{markets++;return market()},emitAlert:async()=>{alerts++},emitDecision:async()=>{},sleep:async()=>{sleeps++},log:()=>{}});const result=await replayPonsLiveLaunch(token,{loadExactLaunch:async()=>row},route,()=>{});assert.equal(result.status,'IGNORED');assert.deepEqual({markets,sleeps,alerts},{markets:0,sleeps:0,alerts:0})}});

test('replay has no checkpoint, dedupe persistence, or real-trading capability',async()=>{let loads=0,realTrades=0,decisions=0;const route=createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>registry('SCAMMER',true),loadMarket:async()=>market(),emitAlert:async()=>{},emitDecision:async()=>{decisions++},sleep:async()=>{},log:()=>{}});const source={loadExactLaunch:async()=>{loads++;return row}};await replayPonsLiveLaunch(token,source,route,()=>{});assert.deepEqual({loads,decisions,realTrades},{loads:1,decisions:0,realTrades:0});assert.deepEqual(Object.keys(source),['loadExactLaunch'])});
