import test from 'node:test';
import assert from 'node:assert/strict';
import type { ChainMarketSnapshot } from '../src/chains/shared/types.js';
import type { PonsDeveloperRegistryEntry } from '../src/chains/robinhood/ponsDeveloperRegistry.js';
import type { PonsLaunch } from '../src/chains/robinhood/ponsHistoricalLaunchScanner.js';
import { createPonsLiveLaunchRouter } from '../src/chains/robinhood/ponsLiveLaunchRouter.js';
import { getPonsLiveConfig } from '../src/chains/robinhood/ponsLiveConfig.js';

const launch: PonsLaunch = { chain:'robinhood',protocol:'pons',protocol_version:'v2-current',factory_address:'0xfactory',token_address:'0xtoken',deployer_address:'0xdeveloper',curve_address:null,pool_address:null,pair_token_address:null,launch_config_id:null,graduation_threshold:null,initial_buy_amount:null,block_number:'10',block_timestamp:'2026-09-04T00:00:00Z',transaction_hash:'0xabc',log_index:1 };
const developer=(tier:string,blocked=false):PonsDeveloperRegistryEntry=>({deployerAddress:launch.deployer_address,tier:tier as never,riskTier:blocked?tier:null,confidence:'HIGH',isBlocked:blocked,blockReason:blocked?'blocked evidence':null,blockedAt:null,totalLaunches:20,usableOutcomes:10,winners100k:4,winners500k:2,winners1m:1,winners5m:0,winners10m:0,bestVerifiedPeakMarketCap:1_500_000,bestTokenAddress:'0xold',hitRate100k:.4,hitRate1m:.1,recent5Hits100k:2,recent5Hits1m:1,severeCrashCount:0,severeCrashRate:0,catastrophicCrashCount:0,catastrophicCrashRate:0,firstLaunchAt:null,latestLaunchAt:null,lastSuccessfulTokenAddress:'0xold',lastSuccessfulPeakMarketCap:1_500_000});
const market=(price=1,marketCap=100_000,buys=10,sells=5):ChainMarketSnapshot=>({chain:'robinhood',tokenAddress:launch.token_address,symbol:'T',name:'Token',priceUsd:price,marketCapUsd:marketCap,liquidityUsd:50_000,volume5mUsd:10_000,buys5m:buys,sells5m:sells,pairAddress:'0xpair',timestamp:Date.now(),source:'DEXSCREENER'});
const config={liveIntelligenceEnabled:true,provenDeveloperAlertsEnabled:true,shadowBuyEnabled:true,confirmationSeconds:0};

test('all live and shadow features default safely disabled',()=>{assert.deepEqual(getPonsLiveConfig({}),{liveIntelligenceEnabled:false,provenDeveloperAlertsEnabled:false,shadowBuyEnabled:false,confirmationSeconds:30})});

test('GEM emits immediately, validates, and UPTREND produces SHADOW BUY',async()=>{let alerts=0,markets=0;const snapshots=[market(),market(1.01,101_000,20,8)];const route=createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>developer('GEM'),loadMarket:async()=>{markets+=1;return snapshots.shift()!},emitAlert:async()=>{alerts+=1},emitDecision:async()=>{},sleep:async()=>{},log:()=>{}});const result=await route(launch);assert.equal(alerts,1);assert.equal(markets,2);assert.equal(result.decision?.momentum,'UPTREND');assert.equal(result.decision?.action,'BUY')});
test('GEM DOWNTREND emits alert but returns SHADOW IGNORE',async()=>{const snapshots=[market(),market(.8,80_000,5,15)];const result=await createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>developer('GEM'),loadMarket:async()=>snapshots.shift()!,emitAlert:async()=>{},emitDecision:async()=>{},sleep:async()=>{},log:()=>{}})(launch);assert.equal(result.alert?.priority,'HIGH');assert.equal(result.decision?.momentum,'DOWNTREND');assert.equal(result.decision?.action,'IGNORE')});
test('missing market evidence fails closed after immediate alert',async()=>{let alerts=0;const result=await createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>developer('GEM'),loadMarket:async()=>null,emitAlert:async()=>{alerts++},emitDecision:async()=>{},sleep:async()=>{},log:()=>{}})(launch);assert.equal(alerts,1);assert.equal(result.decision?.action,'IGNORE');assert.match(result.decision!.reason,/insufficient live market evidence/)});
test('KING and LEGEND use the same priority route',async()=>{for(const tier of ['KING','LEGEND']){let alerts=0;const snapshots=[market(),market(1.01,101_000,20,8)];const result=await createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>developer(tier),loadMarket:async()=>snapshots.shift()!,emitAlert:async()=>{alerts++},emitDecision:async()=>{},sleep:async()=>{},log:()=>{}})(launch);assert.equal(result.provenDeveloper,true);assert.equal(alerts,1)}});
test('SCAMMER and SPAM_LAUNCHER stop before market, momentum, alert, or decision work',async()=>{for(const tier of ['SCAMMER','SPAM_LAUNCHER']){let marketCalls=0,alerts=0,decisions=0,sleeps=0;const result=await createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>developer(tier,true),loadMarket:async()=>{marketCalls++;return market()},emitAlert:async()=>{alerts++},emitDecision:async()=>{decisions++},sleep:async()=>{sleeps++},log:()=>{}})(launch);assert.equal(result.status,'IGNORED');assert.deepEqual({marketCalls,alerts,decisions,sleeps},{marketCalls:0,alerts:0,decisions:0,sleeps:0})}});
test('UNKNOWN and HIGH_RISK never enter proven shadow path',async()=>{for(const tier of ['UNKNOWN','HIGH_RISK']){let marketCalls=0;const result=await createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>developer(tier,tier==='HIGH_RISK'),loadMarket:async()=>{marketCalls++;return market()},emitAlert:async()=>{},emitDecision:async()=>{},sleep:async()=>{},log:()=>{}})(launch);assert.equal(result.status,'NORMAL_PATH');assert.equal(marketCalls,0)}});
test('duplicate launch creates no second alert, confirmation, or decision',async()=>{let alerts=0,markets=0,decisions=0;const route=createPonsLiveLaunchRouter({config,lookupDeveloper:async()=>developer('GEM'),loadMarket:async()=>{markets++;return market()},emitAlert:async()=>{alerts++},emitDecision:async()=>{decisions++},sleep:async()=>{},log:()=>{}});await route(launch);const duplicate=await route(launch);assert.equal(duplicate.status,'DUPLICATE');assert.deepEqual({alerts,markets,decisions},{alerts:1,markets:2,decisions:1})});

test('alert-only mode sends immediately and never starts market, momentum, or shadow decision work',async()=>{let alerts=0,markets=0,sleeps=0,decisions=0;const result=await createPonsLiveLaunchRouter({config:{...config,shadowBuyEnabled:false},lookupDeveloper:async()=>developer('GEM'),loadMarket:async()=>{markets++;return market()},emitAlert:async()=>{alerts++},emitDecision:async()=>{decisions++},sleep:async()=>{sleeps++},log:()=>{}})(launch);assert.equal(result.alertDelivery,'EMITTED');assert.equal(result.decision,null);assert.deepEqual({alerts,markets,sleeps,decisions},{alerts:1,markets:0,sleeps:0,decisions:0})});

test('Telegram failure is concise and contained so launch handling completes',async()=>{const logs:string[]=[];let markets=0;const result=await createPonsLiveLaunchRouter({config:{...config,shadowBuyEnabled:false},lookupDeveloper:async()=>developer('GEM'),loadMarket:async()=>{markets++;return market()},emitAlert:async()=>{throw new Error('<html>'+('cloudflare '.repeat(100))+'</html>')},emitDecision:async()=>{},sleep:async()=>{},log:line=>logs.push(line)})(launch);assert.equal(result.status,'PROVEN_PROCESSED');assert.equal(result.alertDelivery,'FAILED');assert.equal(markets,0);assert.equal(logs.length,1);assert.ok(logs[0].length<250)});
