import { NextResponse } from "next/server";
import { supabaseAdmin } from "@/lib/supabase-admin";
import type { ApiResponse, LiveOpportunity, OpportunitiesResponse, OpportunityStatus, OpportunityType, RiskLevel, Chain } from "@/lib/dashboard/types";
export const dynamic = "force-dynamic"; export const revalidate = 0;
type OpportunityRow = { id:string|number; opportunity_type:string|null; asset_id:string|null; chain:string|null; source_agent:string|null; title:string|null; entry_price:number|string|null; exit_price:number|string|null; expected_profit:number|string|null; expected_profit_percent:number|string|null; risk_score:number|string|null; confidence:number|string|null; status:string|null; raw_data:Record<string,unknown>|null; created_at:string|null; updated_at:string|null };
function toNumber(v:unknown){if(v===null||v===undefined||v==="")return null;const n=Number(v);return Number.isFinite(n)?n:null}
function toStringValue(v:unknown){if(typeof v!=="string")return null;const s=v.trim();return s||null}
function normalizeChain(v:unknown):Chain{const c=String(v??"").trim().toLowerCase();return ["solana","ethereum","base","robinhood","sui","bsc"].includes(c)?c as Chain:"unknown"}
function normalizeOpportunityType(v:unknown):OpportunityType{const n=String(v??"").trim().toUpperCase();const a:OpportunityType[]=["TOKEN_PREDEX","TOKEN_CREATOR","TOKEN_WALLET","DEX_CONFIRMATION","NFT_MISPRICE","NFT_OFFER_ARBITRAGE","CEX_DEX_ARB","PREDICTION_MARKET","NEWS_CATALYST"];return a.includes(n as OpportunityType)?n as OpportunityType:"TOKEN_PREDEX"}
function normalizeStatus(v:unknown):OpportunityStatus{const n=String(v??"").trim().toUpperCase();const a:OpportunityStatus[]=["NEW","WATCHING","APPROVED","EXECUTED","REJECTED","EXPIRED","REVIEWED"];return a.includes(n as OpportunityStatus)?n as OpportunityStatus:"NEW"}
function pickString(r:Record<string,unknown>,keys:string[]){for(const k of keys){const v=toStringValue(r[k]);if(v)return v}return null}
function pickNumber(r:Record<string,unknown>,keys:string[]){for(const k of keys){const v=toNumber(r[k]);if(v!==null)return v}return null}
function normalizeRiskLevel(score:number|null,r:Record<string,unknown>):RiskLevel{const e=String(r.risk_level??r.riskLevel??r.risk??"").trim().toUpperCase();if(["LOW","MEDIUM","HIGH"].includes(e))return e as RiskLevel;if(score===null)return "UNKNOWN";return score<=35?"LOW":score<=70?"MEDIUM":"HIGH"}
function normalizeOpportunity(row:OpportunityRow):LiveOpportunity{const r=row.raw_data&&typeof row.raw_data==="object"&&!Array.isArray(row.raw_data)?row.raw_data:{};const assetId=toStringValue(row.asset_id)??pickString(r,["token","address","mint","tokenAddress","token_address","assetId","asset_id"])??"unknown";const symbol=pickString(r,["symbol","token_symbol","tokenSymbol","ticker"])??toStringValue(row.title)??"UNKNOWN";const token=pickString(r,["token","address","mint","tokenAddress","token_address"])??assetId;const confidence=toNumber(row.confidence)??pickNumber(r,["confidence","score","alpha_score","alphaScore"])??0;const riskScore=toNumber(row.risk_score)??pickNumber(r,["risk_score","riskScore"])??0;const marketCap=pickNumber(r,["market_cap","marketCap","mcap","fdv"]);const athMarketCap=pickNumber(r,["ath_market_cap","athMarketCap","all_time_high_market_cap","allTimeHighMarketCap","peak_market_cap","peakMarketCap","high_market_cap","highMarketCap","market_cap_high","marketCapHigh"]);const liquidity=pickNumber(r,["liquidity","liquidity_usd","liquidityUsd"]);return{id:row.id,opportunityType:normalizeOpportunityType(row.opportunity_type),assetId,token,symbol,title:toStringValue(row.title)??`${symbol} opportunity`,chain:normalizeChain(row.chain),sourceAgent:toStringValue(row.source_agent)??"AlphaOS",confidence:Math.max(0,Math.min(100,Math.round(confidence))),riskScore:Math.max(0,Math.min(100,Math.round(riskScore))),riskLevel:normalizeRiskLevel(riskScore,r),status:normalizeStatus(row.status),expectedProfit:toNumber(row.expected_profit)??pickNumber(r,["expected_profit","expectedProfit"]),expectedProfitPercent:toNumber(row.expected_profit_percent)??pickNumber(r,["expected_profit_percent","expectedProfitPercent","expected_roi","expectedRoi"]),entryPrice:toNumber(row.entry_price)??pickNumber(r,["entry_price","entryPrice","price"]),exitPrice:toNumber(row.exit_price)??pickNumber(r,["exit_price","exitPrice","target_price","targetPrice"]),marketCap,athMarketCap,liquidity,createdAt:row.created_at??new Date().toISOString(),updatedAt:row.updated_at,reportUrl:`/report/${encodeURIComponent(token)}`}}
export async function GET():Promise<NextResponse<ApiResponse<OpportunitiesResponse>>>{try{const{data,error}=await supabaseAdmin.from("opportunities").select("id, opportunity_type, asset_id, chain, source_agent, title, entry_price, exit_price, expected_profit, expected_profit_percent, risk_score, confidence, status, raw_data, created_at, updated_at").in("status",["NEW","WATCHING","APPROVED","new","watching","approved"]).order("created_at",{ascending:false}).limit(12);if(error)throw error;const items=((data??[])as OpportunityRow[]).map(normalizeOpportunity);return NextResponse.json({success:true,data:{items,total:items.length,generatedAt:new Date().toISOString()}})}catch(error){console.error("Live opportunities module failed:",error);return NextResponse.json({success:false,error:"Unable to load live opportunities"},{status:500})}}
