import Link from 'next/link';
import AppShell from '@/components/layout/AppShell';
export default function TokenPage() {
  return <AppShell><main className="premium-page"><div className="premium-container narrow"><p className="premium-eyebrow">ALPHAOS TOKEN · PRE-LAUNCH</p><h1 className="page-title">Product first.<br/>Transparent utility next.</h1><p className="page-intro">AlphaOS is a token intelligence workspace. The proposed token connects eligible holders to research tools—not guaranteed income. Token issuance and holder access are not launched or verified here.</p><div className="hero-actions"><a className="alpha-button-primary" href="/api/open-bot">Explore the bot ↗</a><Link className="premium-button" href="/guide">Learn the tools</Link></div>
    <section className="info-panel"><h2>01 · Explore the product today</h2><p>Use Telegram for supported alerts and fresh contract research. Browse recorded market evidence and creator history on the website. Coverage varies; the website does not verify Telegram membership or token holdings.</p><Link className="text-link" href="/status">Review data coverage →</Link></section>
    <section className="info-panel"><h2>02 · Proposed holder utility</h2><ul><li>Pro tools while the published holding threshold is maintained.</li><li>Larger research and watchlist allowances within sustainable limits.</li><li>Clear eligibility checks with a displayed verification time.</li><li>A subscription alternative for users who prefer direct access.</li></ul><p>Proposals only. Exact thresholds, allowances and eligibility rules must be published and implemented before access is offered.</p></section>
    <section className="info-panel"><h2>03 · Required before token launch</h2><ul><li>Official PONS project, chain and complete token contract address.</li><li>Total supply, allocations, team wallets and vesting schedule.</li><li>Holder access thresholds, verification method and supported benefits.</li><li>Subscription pricing, cancellation and refund terms, and privacy policy.</li><li>Validated data mappings, feature coverage and ongoing delivery checks.</li></ul><div className="data-notice">Official contract: not published. Never treat a similarly named token as AlphaOS. This website does not ask for seed phrases or private keys.</div></section>
    <section className="info-panel"><h2>04 · Grow gradually</h2><p>First validate the research and delivery experience. Then publish the official token rules and implement holder eligibility. Add new tools only after their evidence, reliability and operating cost have been tested.</p><p>Holding a token does not guarantee access before verification is implemented, price appreciation, profit or a share of revenue.</p></section><div className="hero-actions"><Link href="/me" className="premium-button">Compare current access</Link><Link href="/disclosures" className="text-link">Risk & privacy →</Link></div></div></main></AppShell>;
}
