import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
import { supabaseAdmin } from "@/lib/supabase-admin";

export const dynamic = "force-dynamic";
type Props = { params: Promise<{ wallet: string }> };
const money = (value: unknown) => { const n=Number(value); return !Number.isFinite(n)||n<=0 ? "—" : new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:2}).format(n); };
const pct = (value: unknown) => { const n=Number(value); if(!Number.isFinite(n)) return "—"; return `${Math.round((n<=1?n*100:n)*10)/10}%`; };
const short = (value:string) => value.length>24 ? `${value.slice(0,10)}…${value.slice(-8)}` : value;

export default async function DeveloperProfilePage({params}:Props){
 const {wallet}=await params; const decoded=decodeURIComponent(wallet).toLowerCase();
 const [registryResult,launchesResult]=await Promise.all([
  supabaseAdmin.from("pons_developer_registry").select("*").eq("deployer_address",decoded).limit(1).maybeSingle(),
  supabaseAdmin.from("pons_launches").select("token_address,deployer_address,curve_address,pool_address,pair_token_address,block_number,block_timestamp,transaction_hash,protocol,protocol_version").eq("deployer_address",decoded).order("block_timestamp",{ascending:false}).limit(50),
 ]);
 const registry=registryResult.data as Record<string,unknown>|null; const launches=(launchesResult.data??[]) as Record<string,unknown>[];
 const tier=String(registry?.tier??"UNKNOWN"), confidence=String(registry?.confidence??"INSUFFICIENT"), risk=String(registry?.risk_tier??"UNKNOWN");
 const blocked=registry?.is_blocked===true; const winners=Number(registry?.winners_100k??0); const launchesCount=Number(registry?.total_launches??launches.length); const usableOutcomes=Number(registry?.usable_outcomes??0);
 const repeatable=usableOutcomes>=5&&winners>=2&&(confidence==="MEDIUM"||confidence==="HIGH");
 const signal=blocked?"AVOID":repeatable?"PROVEN HISTORY":winners>0?"HIGH PEAK · UNPROVEN":"BUILDING";
 return <AppShell><main className="px-4 pb-28 pt-5 sm:px-6 lg:px-8 lg:pb-10 lg:pt-8"><div className="mx-auto max-w-[1200px]">
  <div className="flex items-center justify-between gap-4"><Link href="/intelligence" className="text-xs text-zinc-500">← Developer Radar</Link><span className="rounded-full border border-emerald-400/15 bg-emerald-400/[0.04] px-3 py-1 text-[9px] text-emerald-300">🟢 PONS INDEXED</span></div>
  <section className="mt-5 rounded-3xl border border-white/[0.08] bg-[#171b1f] p-5 sm:p-7">
   <div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[0.18em] text-emerald-300/80">AlphaOS Developer Fingerprint</p><h1 className="mt-3 break-all font-mono text-lg font-semibold text-white sm:text-2xl">{decoded}</h1><div className="mt-4 flex flex-wrap gap-2">{[tier,confidence,`RISK ${risk}`,`OUTCOMES ${usableOutcomes}`].map(v=><span key={v} className="rounded-full border border-white/[0.08] bg-white/[0.035] px-3 py-1 text-[9px] font-semibold text-zinc-300">{v}</span>)}</div></div>
    <div className={`rounded-2xl border px-5 py-4 ${signal==="AVOID"?"border-rose-400/20 bg-rose-400/[0.05]":signal==="PROVEN HISTORY"?"border-emerald-400/20 bg-emerald-400/[0.05]":"border-white/[0.08] bg-white/[0.025]"}`}><p className="text-[8px] uppercase tracking-[0.15em] text-zinc-600">AlphaOS read</p><p className={`mt-1 text-lg font-semibold ${signal==="AVOID"?"text-rose-300":signal==="PROVEN HISTORY"?"text-emerald-300":"text-zinc-200"}`}>{signal}</p><p className="mt-1 text-[10px] text-zinc-600">{repeatable?"Multiple verified outcomes support repeatability.":winners>0?"Strong historical performance exists, but the sample is still too small to call repeatable.":"History informs attention. Token security still decides eligibility."}</p></div></div>
   <div className="mt-7 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8"><Stat label="Launches" value={String(launchesCount)}/><Stat label="Verified outcomes" value={String(usableOutcomes)}/><Stat label="$100K+" value={String(registry?.winners_100k??0)}/><Stat label="$500K+" value={String(registry?.winners_500k??0)}/><Stat label="$1M+" value={String(registry?.winners_1m??0)}/><Stat label="100K hit" value={pct(registry?.hit_rate_100k)}/><Stat label="Crash rate" value={pct(registry?.severe_crash_rate)}/><Stat label="Best peak" value={money(registry?.best_verified_peak_market_cap)}/></div>
  </section>
  <section className="mt-4 grid gap-3 md:grid-cols-3"><IntelCard title="Track record" value={winners>0?`${winners} verified $100K+ winner${winners===1?"":"s"}`:"No verified $100K winner yet"} body={repeatable?"Repeatability threshold met using multiple verified outcomes.":"Historical wins are shown separately from repeatability confidence."}/><IntelCard title="Launch cadence" value={`${launchesCount} indexed launch${launchesCount===1?"":"es"}`} body={registry?.latest_launch_at?`Latest ${new Date(String(registry.latest_launch_at)).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric"})}`:"Latest launch not yet verified."}/><IntelCard title="Risk memory" value={blocked?"BLOCKED":risk} body="Serial spam, scam and severe outcome evidence remain visible to the routing layer." danger={blocked}/></section>
  <section className="mt-4 overflow-hidden rounded-3xl border border-white/[0.08] bg-[#15191d]"><div className="border-b border-white/[0.07] px-5 py-4 sm:px-6"><p className="text-sm font-semibold text-white">Contract-by-Contract History</p><p className="mt-1 text-[11px] text-zinc-600">Every indexed PONS launch linked to this deployer. Open a token for its intelligence view.</p></div>
   {launchesResult.error?<div className="p-6 text-sm text-amber-300">Project history is temporarily unavailable.</div>:launches.length===0?<div className="p-6 text-sm text-zinc-500">No indexed launches found yet.</div>:<div className="divide-y divide-white/[0.055]">{launches.map((launch,index)=>{const token=String(launch.token_address??"");return <div key={`${token}-${String(launch.transaction_hash??"")}`} className="grid gap-3 px-5 py-4 sm:px-6 lg:grid-cols-[.25fr_1.3fr_.7fr_.7fr_.5fr] lg:items-center"><div className="text-xs font-semibold text-zinc-600">#{index+1}</div><div><p className="text-[8px] uppercase tracking-[0.13em] text-zinc-600">Contract</p><p className="mt-1 font-mono text-xs text-zinc-200">{short(token)}</p></div><div><p className="text-[8px] uppercase tracking-[0.13em] text-zinc-600">Launched</p><p className="mt-1 text-xs text-zinc-300">{launch.block_timestamp?new Date(String(launch.block_timestamp)).toLocaleString("en-US",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}):"—"}</p></div><div><p className="text-[8px] uppercase tracking-[0.13em] text-zinc-600">Protocol</p><p className="mt-1 text-xs text-emerald-300">🟢 {String(launch.protocol??"PONS")} {String(launch.protocol_version??"")}</p></div><Link href={`/intelligence/${encodeURIComponent(token)}?chain=robinhood`} className="flex min-h-9 items-center justify-center rounded-xl border border-white/[0.08] px-3 text-[10px] text-zinc-300 transition hover:bg-white/[0.04]">Open token →</Link></div>})}</div>}
  </section>
 </div></main></AppShell>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/[0.07] bg-[#1c2125] p-3.5"><p className="text-[8px] uppercase tracking-[0.13em] text-zinc-600">{label}</p><p className="mt-1.5 text-sm font-semibold text-white">{value}</p></div>}
function IntelCard({title,value,body,danger=false}:{title:string;value:string;body:string;danger?:boolean}){return <div className={`rounded-2xl border p-4 ${danger?"border-rose-400/15 bg-rose-400/[0.035]":"border-white/[0.07] bg-[#171b1f]"}`}><p className="text-[8px] uppercase tracking-[0.14em] text-zinc-600">{title}</p><p className={`mt-2 text-sm font-semibold ${danger?"text-rose-300":"text-zinc-100"}`}>{value}</p><p className="mt-1.5 text-[10px] leading-4 text-zinc-600">{body}</p></div>}
