"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { ApiResponse, LiveOpportunity, OpportunitiesResponse } from "@/lib/dashboard/types";

type WindowKey = "today" | "7d";
type ChainFilter = "all" | "solana" | "robinhood";
type AlertItem = { id:string; token:string; symbol:string; name:string|null; chain:"solana"|"robinhood"|"unknown"; score:number|null; alertPrice:number|null; currentPrice:number|null; peakPrice:number|null; roiHigh:number|null; roiNow:number|null; alertedAt:string|null };
type TopAlertResponse = { window:WindowKey; solanaLeaders:AlertItem[]; robinhoodLeaders:AlertItem[]; recent:AlertItem[]; summary:{tracked:number;winners:number;over100:number;medianPeak:number|null} };

const windows:[WindowKey,string][] = [["today","Today"],["7d","Last 7 Days"]];
function meta(c:string){return c==="robinhood"?{label:"ROBINHOOD · PONS",text:"text-emerald-300",border:"border-emerald-400/20"}:c==="solana"?{label:"SOLANA",text:"text-violet-300",border:"border-violet-400/20"}:{label:"CHAIN",text:"text-zinc-400",border:"border-white/10"}}
function pct(v:number|null){return v===null?"—":`${v>=0?"+":""}${v.toFixed(Math.abs(v)>=100?0:1)}%`}
function money(v:number|null|undefined){return v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(v)}
function price(v:number|null|undefined){if(v==null)return"—";if(v>=1)return`$${v.toLocaleString("en-US",{maximumFractionDigits:4})}`;return `$${v.toLocaleString("en-US",{minimumFractionDigits:Math.min(8,Math.max(4,Math.ceil(-Math.log10(v))+3)),maximumFractionDigits:10})}`}
function ago(v:string|null){if(!v)return"—";const m=Math.floor(Math.max(Date.now()-new Date(v).getTime(),0)/60000);if(m<60)return`${Math.max(m,1)}m`;const h=Math.floor(m/60);return h<24?`${h}h`:`${Math.floor(h/24)}d`}
function Pill({chain}:{chain:string}){const m=meta(chain);return <span className={`rounded-full border ${m.border} bg-white/[0.035] px-2.5 py-1 text-[9px] font-semibold tracking-[0.12em] ${m.text}`}>{m.label}</span>}
function alertUrl(a:AlertItem){const p=new URLSearchParams({chain:a.chain,symbol:a.symbol,confidence:String(a.score??0)});return `/intelligence/${encodeURIComponent(a.token)}?${p}`}
function intelligence(i:LiveOpportunity){const p=new URLSearchParams({chain:i.chain,symbol:i.symbol,source:i.sourceAgent||"AlphaOS",confidence:String(i.confidence),risk:i.riskLevel});if(i.marketCap!==null)p.set("marketCap",String(i.marketCap));return `/intelligence/${encodeURIComponent(i.token)}?${p}`}

function Leaderboard({title,chain,items}:{title:string;chain:"solana"|"robinhood";items:AlertItem[]}){
  return <section className="overflow-hidden rounded-3xl border border-white/[0.08] bg-[#171b1f]">
    <div className="flex items-center justify-between border-b border-white/[0.07] px-4 py-4 sm:px-5"><div><Pill chain={chain}/><h3 className="mt-2 text-lg font-semibold">{title}</h3></div><span className="text-[9px] tracking-[0.14em] text-zinc-600">TOP 5</span></div>
    <div>{items.length?items.map((a,n)=><Link href={alertUrl(a)} key={a.id} className={`block px-4 py-4 transition hover:bg-white/[0.025] sm:px-5 ${n?"border-t border-white/[0.06]":""}`}>
      <div className="flex items-center gap-3"><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-xs font-semibold ${n===0?"bg-amber-300/[0.10] text-amber-200":"bg-white/[0.04] text-zinc-500"}`}>#{n+1}</div><div className="min-w-0 flex-1"><p className="truncate text-base font-semibold">{a.symbol}</p><p className="mt-0.5 text-[9px] text-zinc-600">Alerted {ago(a.alertedAt)} ago · Alpha {a.score??"—"}</p></div><div className="text-right"><p className="text-xl font-semibold text-emerald-300">{pct(a.roiHigh)}</p><p className="text-[8px] tracking-wider text-zinc-600">MAX MOVE</p></div></div>
      <div className="mt-3 grid grid-cols-3 gap-1.5"><div className="rounded-xl bg-white/[0.025] p-2.5"><p className="text-[8px] text-zinc-600">ALERT PRICE</p><p className="mt-1 truncate text-[11px] font-semibold">{price(a.alertPrice)}</p></div><div className="rounded-xl bg-amber-300/[0.035] p-2.5"><p className="text-[8px] text-zinc-600">{chain==="robinhood"?"ATH":"RECORDED PEAK"}</p><p className="mt-1 truncate text-[11px] font-semibold text-amber-200">{price(a.peakPrice)}</p></div><div className="rounded-xl bg-white/[0.025] p-2.5"><p className="text-[8px] text-zinc-600">CURRENT</p><p className="mt-1 truncate text-[11px] font-semibold">{price(a.currentPrice)}</p><p className={`mt-0.5 text-[8px] ${(a.roiNow??0)>=0?"text-emerald-300":"text-red-300"}`}>{pct(a.roiNow)}</p></div></div>
    </Link>):<p className="px-5 py-8 text-center text-sm text-zinc-600">No tracked alerts in this window yet.</p>}</div>
  </section>
}

function OpportunityCard({item}:{item:LiveOpportunity}){
  const m=meta(item.chain);
  const fromAth=item.marketCap&&item.athMarketCap&&item.athMarketCap>0?(item.marketCap/item.athMarketCap-1)*100:null;
  const peakLabel=item.chain==="robinhood"?"ATH MARKET CAP":"RECORDED PEAK MC";
  return <article className="rounded-2xl border border-white/[0.08] bg-[#181d21] p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><Pill chain={item.chain}/><h3 className="mt-3 text-xl font-semibold">{item.symbol}</h3><p className="mt-1 text-[10px] uppercase tracking-wider text-zinc-500">{item.status}</p></div><div className="rounded-xl border border-white/[0.07] bg-white/[0.035] px-3 py-2 text-right"><p className={`text-2xl font-semibold ${m.text}`}>{item.confidence}</p><p className="text-[8px] tracking-[0.14em] text-zinc-500">ALPHA</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/[0.025] p-3"><p className="text-[8px] text-zinc-500">MARKET CAP</p><p className="mt-1 text-sm font-semibold">{money(item.marketCap)}</p></div><div className="rounded-xl bg-amber-300/[0.035] p-3"><p className="text-[8px] text-zinc-500">{peakLabel}</p><p className="mt-1 text-sm font-semibold text-amber-200">{money(item.athMarketCap)}</p>{fromAth!==null?<p className="mt-0.5 text-[8px] text-zinc-500">{pct(fromAth)} from peak</p>:null}</div></div><Link href={intelligence(item)} className="mt-4 flex min-h-11 items-center justify-center rounded-xl border border-emerald-300/25 bg-emerald-300/[0.08] px-3 text-xs font-semibold text-emerald-200">Open Intelligence →</Link></article>
}

export default function AlphaHome(){
  const[w,setW]=useState<WindowKey>("today"),[performance,setPerformance]=useState<TopAlertResponse|null>(null),[opps,setOpps]=useState<LiveOpportunity[]>([]),[chain,setChain]=useState<ChainFilter>("all"),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);try{const[a,b]=await Promise.all([fetch(`/api/top-alerts?window=${w}`,{cache:"no-store"}),fetch("/api/opportunities",{cache:"no-store"})]);const x=await a.json() as ApiResponse<TopAlertResponse>,y=await b.json() as ApiResponse<OpportunitiesResponse>;if(x.success)setPerformance(x.data);if(y.success)setOpps(y.data.items)}finally{setLoading(false)}},[w]);
  useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>opps.filter(i=>chain==="all"||i.chain===chain).slice(0,4),[opps,chain]);
  const recent=performance?.recent??[];
  const winRate=performance?.summary.tracked?Math.round(performance.summary.winners/performance.summary.tracked*100):0;
  return <main className="px-4 pb-28 pt-5 sm:px-6 lg:px-8 lg:pb-10 lg:pt-8"><div className="mx-auto max-w-[1180px]">
    <section className="mb-5"><p className="text-[10px] font-semibold tracking-[0.18em] text-emerald-300">● ALPHAOS LIVE INTELLIGENCE</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Proof first. <span className="text-zinc-400">Then the next opportunity.</span></h1><p className="mt-2 text-sm text-zinc-500">Real AlphaOS alert performance across Solana and Robinhood · PONS.</p></section>
    <div className="mb-4 flex max-w-sm gap-1 rounded-xl border border-white/[0.08] bg-[#171b1f] p-1">{windows.map(([k,l])=><button key={k} onClick={()=>setW(k)} className={`flex-1 rounded-lg px-3 py-2.5 text-xs ${w===k?"bg-white/[0.09] text-white":"text-zinc-500"}`}>{l}</button>)}</div>
    <div className="grid gap-4 lg:grid-cols-2"><Leaderboard title="Solana Top Alerts" chain="solana" items={performance?.solanaLeaders??[]}/><Leaderboard title="Robinhood · PONS Top Alerts" chain="robinhood" items={performance?.robinhoodLeaders??[]}/></div>
    {loading?<p className="mt-3 text-xs text-zinc-600">Refreshing verified alert performance…</p>:null}
    {performance?<section className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["ALERTS TRACKED",performance.summary.tracked],["POSITIVE PEAKS",`${winRate}%`],["100%+ RUNNERS",performance.summary.over100],["MEDIAN WINNER PEAK",pct(performance.summary.medianPeak)]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/[0.08] bg-[#171b1f] p-4"><p className="text-[8px] text-zinc-500">{l}</p><p className="mt-1.5 text-xl font-semibold">{v}</p></div>)}</section>:null}

    <section className="mt-9"><div className="flex items-end justify-between"><div><p className="text-[10px] font-semibold tracking-[0.18em] text-zinc-400">● LIVE RADAR</p><h2 className="mt-2 text-2xl font-semibold">What AlphaOS sees now</h2></div><Link href="/opportunities" className="text-xs text-zinc-300">View all →</Link></div><div className="mt-4 flex gap-1 rounded-xl border border-white/[0.08] bg-[#171b1f] p-1">{(["all","solana","robinhood"] as ChainFilter[]).map(c=><button key={c} onClick={()=>setChain(c)} className={`flex-1 rounded-lg px-2 py-2 text-[10px] font-semibold ${chain===c?"bg-white/[0.09] text-white":"text-zinc-500"}`}>{c==="all"?"ALL":c==="solana"?"SOLANA":"ROBINHOOD · PONS"}</button>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2">{visible.map(i=><OpportunityCard key={String(i.id)} item={i}/>)}</div></section>

    <section className="mt-9 pb-3"><div className="flex items-end justify-between"><div><p className="text-[10px] font-semibold tracking-[0.18em] text-zinc-500">LATEST ALERTS</p><h2 className="mt-2 text-xl font-semibold">Alert performance tape</h2></div><p className="text-[9px] text-zinc-600">Alert → Peak → Now</p></div><div className="mt-4 overflow-hidden rounded-2xl border border-white/[0.08] bg-[#171b1f]">{recent.map((a,n)=><Link href={alertUrl(a)} key={a.id} className={`grid grid-cols-[44px_1fr_auto] items-center gap-3 px-4 py-3.5 sm:grid-cols-[52px_1fr_120px_120px_120px] ${n?"border-t border-white/[0.06]":""}`}><div className="text-[10px] text-zinc-600">{ago(a.alertedAt)}</div><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold">{a.symbol}</p><Pill chain={a.chain}/></div></div><div className="hidden text-right sm:block"><p className="text-[8px] text-zinc-600">ALERT PRICE</p><p className="mt-1 text-[11px] text-zinc-300">{price(a.alertPrice)}</p></div><div className="hidden text-right sm:block"><p className="text-[8px] text-zinc-600">{a.chain==="robinhood"?"ATH":"RECORDED PEAK"}</p><p className="mt-1 text-[11px] text-amber-200">{price(a.peakPrice)}</p><p className="text-[8px] text-emerald-300">{pct(a.roiHigh)}</p></div><div className="text-right"><p className="text-[8px] text-zinc-600">CURRENT</p><p className="mt-1 text-[11px]">{price(a.currentPrice)}</p><p className={`text-[8px] ${(a.roiNow??0)>=0?"text-emerald-300":"text-red-300"}`}>{pct(a.roiNow)}</p></div></Link>)}</div></section>
  </div></main>;
}
