"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { ApiResponse } from "@/lib/dashboard/types";

type WindowKey = "today" | "7d";
type AlertItem = { id:string; token:string; symbol:string; name:string|null; chain:"solana"|"robinhood"|"unknown"; score:number|null; alertPrice:number|null; currentPrice:number|null; peakPrice:number|null; roiHigh:number|null; roiNow:number|null; alertedAt:string|null };
type TopAlertResponse = { window:WindowKey; solanaLeaders:AlertItem[]; robinhoodLeaders:AlertItem[]; recent:AlertItem[]; summary:{tracked:number;winners:number;over100:number;medianPeak:number|null} };

const windows:[WindowKey,string][] = [["today","Today"],["7d","7 Days"]];
function meta(c:string){return c==="robinhood"?{label:"PONS",text:"text-emerald-300",border:"border-emerald-400/20"}:c==="solana"?{label:"SOLANA",text:"text-violet-300",border:"border-violet-400/20"}:{label:"CHAIN",text:"text-zinc-400",border:"border-white/10"}}
function pct(v:number|null){return v===null?"—":`${v>=0?"+":""}${v.toFixed(Math.abs(v)>=100?0:1)}%`}
function price(v:number|null|undefined){if(v==null)return"—";if(v>=1)return`$${v.toLocaleString("en-US",{maximumFractionDigits:4})}`;return `$${v.toLocaleString("en-US",{minimumFractionDigits:Math.min(8,Math.max(4,Math.ceil(-Math.log10(v))+3)),maximumFractionDigits:10})}`}
function ago(v:string|null){if(!v)return"—";const m=Math.floor(Math.max(Date.now()-new Date(v).getTime(),0)/60000);if(m<60)return`${Math.max(m,1)}m`;const h=Math.floor(m/60);return h<24?`${h}h`:`${Math.floor(h/24)}d`}
function Pill({chain}:{chain:string}){const m=meta(chain);return <span className={`rounded-full border ${m.border} bg-white/[0.035] px-2 py-1 text-[8px] font-semibold tracking-[0.12em] ${m.text}`}>{m.label}</span>}
function alertUrl(a:AlertItem){const p=new URLSearchParams({chain:a.chain,symbol:a.symbol});if(a.score!=null)p.set("confidence",String(a.score));return `/intelligence/${encodeURIComponent(a.token)}?${p}`}

function WinnerCard({a,n}:{a:AlertItem;n:number}){return <Link href={alertUrl(a)} className="block rounded-3xl border border-white/[0.08] bg-[#171b1f] p-4 transition hover:border-emerald-400/20"><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl text-xs font-bold ${n===0?"bg-amber-300/[0.12] text-amber-200":"bg-white/[0.04] text-zinc-400"}`}>#{n+1}</div><div><div className="flex items-center gap-2"><p className="font-semibold">{a.symbol}</p><Pill chain={a.chain}/></div><p className="mt-1 text-[9px] text-zinc-600">Alerted {ago(a.alertedAt)} ago · Alpha {a.score??"verified"}</p></div></div><div className="text-right"><p className="text-2xl font-semibold text-emerald-300">{pct(a.roiHigh)}</p><p className="text-[8px] uppercase tracking-wider text-zinc-600">max move</p></div></div><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl bg-white/[0.025] p-2.5"><p className="text-[7px] text-zinc-600">ALERT</p><p className="mt-1 truncate text-[10px] font-semibold">{price(a.alertPrice)}</p></div><div className="rounded-xl bg-amber-300/[0.035] p-2.5"><p className="text-[7px] text-zinc-600">PEAK</p><p className="mt-1 truncate text-[10px] font-semibold text-amber-200">{price(a.peakPrice)}</p></div><div className="rounded-xl bg-white/[0.025] p-2.5"><p className="text-[7px] text-zinc-600">CURRENT</p><p className="mt-1 truncate text-[10px] font-semibold">{price(a.currentPrice)}</p></div></div></Link>}

export default function AlphaHome(){
 const[w,setW]=useState<WindowKey>("today"),[performance,setPerformance]=useState<TopAlertResponse|null>(null),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);try{const response=await fetch(`/api/top-alerts?window=${w}`,{cache:"no-store"});const payload=await response.json() as ApiResponse<TopAlertResponse>;if(payload.success)setPerformance(payload.data)}finally{setLoading(false)}},[w]);
 useEffect(()=>{void load()},[load]);
 const recent=performance?.recent??[];
 const winners=useMemo(()=>[...(performance?.solanaLeaders??[]),...(performance?.robinhoodLeaders??[])].filter(a=>a.roiHigh!=null).sort((a,b)=>(b.roiHigh??-Infinity)-(a.roiHigh??-Infinity)),[performance]);
 const winRate=performance?.summary.tracked?Math.round(performance.summary.winners/performance.summary.tracked*100):null;
 const best=winners[0]?.roiHigh??null;
 return <main className="px-4 pb-32 pt-5 sm:px-6 lg:px-8 lg:pb-12 lg:pt-8"><div className="mx-auto max-w-[1100px]">
   <section className="relative overflow-hidden rounded-[28px] border border-emerald-400/15 bg-[radial-gradient(circle_at_85%_10%,rgba(52,211,153,.12),transparent_35%),#171b1f] px-5 py-7 sm:px-8 sm:py-10"><p className="text-[9px] font-semibold tracking-[0.2em] text-emerald-300">● ALPHAOS IS LIVE</p><h1 className="mt-3 max-w-2xl text-3xl font-semibold leading-[1.05] tracking-[-0.045em] sm:text-5xl">Find opportunities before the crowd.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-400">AI-powered Solana + PONS intelligence. See what AlphaOS caught, what it is tracking, and get qualified alerts directly in Telegram.</p><div className="mt-6 flex gap-2"><Link href="/me" className="rounded-xl bg-emerald-300 px-4 py-3 text-xs font-bold text-[#0c1511]">Get AlphaOS Alerts →</Link><a href="#proof" className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-xs font-semibold text-white">See Results</a></div></section>

   <section className="mt-3 grid grid-cols-4 gap-2">{[["ALERTS",performance?.summary.tracked??"—"],["WIN RATE",winRate==null?"—":`${winRate}%`],["BEST MOVE",pct(best)],["100%+",performance?.summary.over100??"—"]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/[0.07] bg-[#171b1f] px-2 py-3 text-center"><p className="text-[7px] tracking-wider text-zinc-600">{l}</p><p className="mt-1 text-base font-semibold">{v}</p></div>)}</section>

   <section id="proof" className="mt-9"><div className="flex items-end justify-between gap-4"><div><p className="text-[9px] font-semibold tracking-[0.18em] text-amber-200">🏆 VERIFIED RESULTS</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">AlphaOS winners</h2><p className="mt-1 text-xs text-zinc-500">Measured from recorded alert price to recorded peak.</p></div><div className="flex rounded-lg border border-white/[0.08] bg-[#171b1f] p-1">{windows.map(([k,l])=><button key={k} onClick={()=>setW(k)} className={`rounded-md px-2.5 py-2 text-[9px] ${w===k?"bg-white/[0.09] text-white":"text-zinc-500"}`}>{l}</button>)}</div></div><div className="mt-4 grid gap-3 lg:grid-cols-3">{winners.slice(0,3).map((a,n)=><WinnerCard key={a.id} a={a} n={n}/>)}</div>{!winners.length&&!loading?<div className="mt-4 rounded-2xl border border-white/[0.08] bg-[#171b1f] p-6 text-sm text-zinc-500">Verified results are refreshing.</div>:null}</section>

   <section className="mt-10"><div className="flex items-end justify-between"><div><p className="text-[9px] font-semibold tracking-[0.18em] text-emerald-300">⚡ LIVE FEED</p><h2 className="mt-2 text-2xl font-semibold">Latest 10 alerts</h2><p className="mt-1 text-xs text-zinc-500">Not hand-picked. Latest measured AlphaOS alerts.</p></div><Link href="/opportunities" className="text-[10px] font-semibold text-emerald-300">Open Radar →</Link></div><div className="mt-4 overflow-hidden rounded-2xl border border-white/[0.08] bg-[#171b1f]">{recent.slice(0,10).map((a,n)=><Link href={alertUrl(a)} key={a.id} className={`grid grid-cols-[42px_1fr_auto] items-center gap-3 px-4 py-3.5 ${n?"border-t border-white/[0.06]":""}`}><div className="text-[9px] text-zinc-600">{ago(a.alertedAt)}</div><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-sm font-semibold">{a.symbol}</p><Pill chain={a.chain}/></div><p className="mt-1 text-[8px] text-zinc-600">Alert {price(a.alertPrice)}</p></div><div className="text-right"><p className={`text-sm font-semibold ${(a.roiHigh??0)>=0?"text-emerald-300":"text-red-300"}`}>{pct(a.roiHigh)}</p><p className="text-[7px] text-zinc-600">MAX MOVE</p></div></Link>)}</div></section>

   <section className="mt-10 grid gap-3 sm:grid-cols-3">{[["🧠","Developer Intelligence","Follow proven developer launch history."],["💰","Smart Money","Rank wallets by measured outcomes, not hype."],["🐋","Wallet Tracking","Track wallets and surface meaningful activity."]].map(([i,t,d])=><Link href="/intelligence" key={t} className="rounded-2xl border border-white/[0.08] bg-[#171b1f] p-4"><p className="text-lg">{i}</p><p className="mt-2 text-sm font-semibold">{t}</p><p className="mt-1 text-[10px] leading-4 text-zinc-500">{d}</p></Link>)}</section>

   <section className="mt-10 rounded-[28px] border border-emerald-400/15 bg-emerald-400/[0.045] p-6 text-center sm:p-8"><p className="text-[9px] font-semibold tracking-[0.18em] text-emerald-300">GET THE ALERT, NOT THE HINDSIGHT</p><h2 className="mx-auto mt-2 max-w-lg text-2xl font-semibold">See AlphaOS intelligence when the opportunity appears.</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-zinc-500">Start with AlphaOS access and unlock the bot, wallet intelligence and live opportunity workflow.</p><Link href="/me" className="mt-5 inline-block rounded-xl bg-emerald-300 px-5 py-3 text-xs font-bold text-[#0c1511]">Get AlphaOS →</Link></section>
   {loading?<p className="mt-3 text-center text-[9px] text-zinc-700">Refreshing verified AlphaOS performance…</p>:null}
 </div></main>
}
