declare global { interface Array<T> { at(index: number): T | undefined } }
export type PonsLaunchCensusRow={token_address:string;deployer_address:string;protocol_version:string;block_timestamp:string};
export type ExistingCreatorOutcomeRow={token:string;creator_wallet?:string|null;peak_market_cap?:number|string|null;current_market_cap?:number|string|null;crossed_100k?:boolean|null;crossed_500k?:boolean|null;crossed_1m?:boolean|null;severe_crash?:boolean|null;catastrophic_crash?:boolean|null;tracking_complete?:boolean|null;last_checked_at?:string|null};
export type PonsNativeOutcomeRow={token_address:string;peak_market_cap?:number|string|null;current_market_cap?:number|string|null;crossed_100k?:boolean|null;crossed_500k?:boolean|null;crossed_1m?:boolean|null;crossed_5m?:boolean|null;crossed_10m?:boolean|null;severe_crash?:boolean|null;catastrophic_crash?:boolean|null;data_confidence?:string|null;last_checked_at?:string|null};
export type PonsTokenOutcome={tokenAddress:string;deployerAddress:string;protocolVersion:string;launchedAt:string;peakMarketCap:number|null;currentMarketCap:number|null;crossed100k:boolean|null;crossed500k:boolean|null;crossed1m:boolean|null;crossed5m:boolean|null;crossed10m:boolean|null;severeCrash:boolean|null;catastrophicCrash:boolean|null;usable:boolean;trackingStatus:'COMPLETE'|'PARTIAL'|'UNKNOWN';dataConfidence:'VERIFIED'|'PARTIAL'|'UNKNOWN';outcomeSource:'PONS_NATIVE_EXACT_TOKEN'|'CREATOR_LAUNCHES_EXACT_TOKEN'|'NONE';lastCheckedAt:string|null};
export type PonsDeveloperTier='LEGEND'|'KING'|'GEM'|'PROVEN'|'PROMISING'|'UNKNOWN'|'HIGH_RISK'|'SPAM_LAUNCHER'|'SCAMMER';
export type PonsRiskTier='HIGH_RISK'|'SPAM_LAUNCHER'|'SCAMMER'|null;
export type PonsSampleConfidence='HIGH'|'MEDIUM'|'LOW'|'INSUFFICIENT';
export type PonsDeveloperIntelligence={developerAddress:string;totalPonsLaunches:number;launchesWithUsableOutcomes:number;winners100k:number;winners500k:number;winners1m:number;winners5m:number;winners10m:number;bestKnownPeakMarketCap:number|null;bestTokenAddress:string|null;hitRate100k:number|null;hitRate1m:number|null;recent5Hits100k:number;recent5Hits1m:number;recent5HitRate100k:number|null;severeCrashCount:number;severeCrashRate:number|null;catastrophicCrashCount:number;catastrophicCrashRate:number|null;firstLaunch:string|null;latestLaunch:string|null;lastSuccessfulTokenAddress:string|null;lastSuccessfulPeakMarketCap:number|null;sampleConfidence:PonsSampleConfidence;tier:PonsDeveloperTier;riskTier:PonsRiskTier;isBlocked:boolean;blockReason:string|null;outcomes:PonsTokenOutcome[]};
export type PonsOutcomeDataSource={loadPonsLaunches(deployerAddress?:string):Promise<PonsLaunchCensusRow[]>;loadCreatorOutcomes(tokens:string[]):Promise<ExistingCreatorOutcomeRow[]>;loadPonsNativeOutcomes?(tokens:string[]):Promise<PonsNativeOutcomeRow[]>};
const lower=(v:string)=>v.trim().toLowerCase();
const number=(v:unknown)=>{const n=Number(v);return v==null||v===''||!Number.isFinite(n)||n<=0?null:n};
const flag=(peak:number|null,n:number,stored?:boolean|null):boolean|null=>peak!=null?peak>=n:stored===true?true:null;
const rate=(a:number,b:number)=>b?a/b:null;

export function bridgePonsTokenOutcomes(launches:PonsLaunchCensusRow[],creatorRows:ExistingCreatorOutcomeRow[],nativeRows:PonsNativeOutcomeRow[]=[]):PonsTokenOutcome[]{
 const creators=new Map(creatorRows.filter(x=>x.token).map(x=>[lower(x.token),x]));const natives=new Map(nativeRows.filter(x=>x.token_address).map(x=>[lower(x.token_address),x]));
 return launches.map(l=>{const n=natives.get(lower(l.token_address)),c=creators.get(lower(l.token_address)),nv=n?.data_confidence==='VERIFIED_HISTORY';const peak=nv?number(n?.peak_market_cap):c?.tracking_complete?number(c.peak_market_cap):null;const verified=nv||c?.tracking_complete===true||c?.severe_crash===true||c?.catastrophic_crash===true;const stored=(a?:boolean|null,b?:boolean|null)=>nv?a:c?.tracking_complete?b:null;return {tokenAddress:lower(l.token_address),deployerAddress:lower(l.deployer_address),protocolVersion:l.protocol_version,launchedAt:l.block_timestamp,peakMarketCap:peak,currentMarketCap:number(n?.current_market_cap)??number(c?.current_market_cap),crossed100k:flag(peak,1e5,stored(n?.crossed_100k,c?.crossed_100k)),crossed500k:flag(peak,5e5,stored(n?.crossed_500k,c?.crossed_500k)),crossed1m:flag(peak,1e6,stored(n?.crossed_1m,c?.crossed_1m)),crossed5m:flag(peak,5e6,nv?n?.crossed_5m:null),crossed10m:flag(peak,1e7,nv?n?.crossed_10m:null),severeCrash:verified?(n?.severe_crash??c?.severe_crash)===true:null,catastrophicCrash:verified?(n?.catastrophic_crash??c?.catastrophic_crash)===true:null,usable:verified,trackingStatus:nv||c?.tracking_complete?'COMPLETE':n||c?'PARTIAL':'UNKNOWN',dataConfidence:verified?'VERIFIED':n||c?'PARTIAL':'UNKNOWN',outcomeSource:n?'PONS_NATIVE_EXACT_TOKEN':c?'CREATOR_LAUNCHES_EXACT_TOKEN':'NONE',lastCheckedAt:n?.last_checked_at??c?.last_checked_at??null};});
}
export function classifyPonsDeveloper(a:{totalLaunches:number;usable:number;winners100k:number;winners500k:number;winners1m:number;winners5m:number;winners10m:number;hitRate100k:number|null;severeCrashRate:number|null;catastrophicCrashes:number}):PonsDeveloperTier{
 if(a.totalLaunches>=20&&a.usable>=10&&a.winners100k===0&&a.winners1m===0&&(a.severeCrashRate??0)>=.7)return'SCAMMER';
 if(a.totalLaunches>=50&&a.winners100k===0)return'SPAM_LAUNCHER';
 if(a.usable>=5&&(a.catastrophicCrashes>=2||(a.severeCrashRate??0)>=.6))return'HIGH_RISK';
 if(a.winners10m>=1||a.winners5m>=2)return'LEGEND';if(a.winners5m>=1||a.winners1m>=3)return'KING';if(a.winners1m>=1)return'GEM';if(a.usable>=8&&a.winners100k>=4&&(a.hitRate100k??0)>=.5)return'PROVEN';if(a.usable>=1&&a.winners100k>=1)return'PROMISING';return'UNKNOWN';
}
export function aggregatePonsDeveloperIntelligence(outcomes:PonsTokenOutcome[]):PonsDeveloperIntelligence[]{
 const groups=new Map<string,PonsTokenOutcome[]>();for(const x of outcomes)groups.set(x.deployerAddress,[...(groups.get(x.deployerAddress)??[]),x]);
 const result=[...groups].map(([developerAddress,all])=>{const chronological=[...all].sort((a,b)=>a.launchedAt.localeCompare(b.launchedAt)||a.tokenAddress.localeCompare(b.tokenAddress)),usable=chronological.filter(x=>x.usable),count=(k:'crossed100k'|'crossed500k'|'crossed1m'|'crossed5m'|'crossed10m')=>usable.filter(x=>x[k]===true).length;const winners100k=count('crossed100k'),winners500k=count('crossed500k'),winners1m=count('crossed1m'),winners5m=count('crossed5m'),winners10m=count('crossed10m'),severeCrashCount=usable.filter(x=>x.severeCrash===true).length,catastrophicCrashCount=usable.filter(x=>x.catastrophicCrash===true).length,recent=usable.slice(-5),hitRate100k=rate(winners100k,usable.length),severeCrashRate=rate(severeCrashCount,usable.length),best=usable.filter(x=>x.peakMarketCap!=null).sort((a,b)=>b.peakMarketCap!-a.peakMarketCap!||a.tokenAddress.localeCompare(b.tokenAddress))[0],lastSuccess=[...usable].reverse().find(x=>x.crossed100k===true);const tier=classifyPonsDeveloper({totalLaunches:all.length,usable:usable.length,winners100k,winners500k,winners1m,winners5m,winners10m,hitRate100k,severeCrashRate,catastrophicCrashes:catastrophicCrashCount}),riskTier:PonsRiskTier=tier==='SCAMMER'||tier==='SPAM_LAUNCHER'||tier==='HIGH_RISK'?tier:null;return {developerAddress,totalPonsLaunches:all.length,launchesWithUsableOutcomes:usable.length,winners100k,winners500k,winners1m,winners5m,winners10m,bestKnownPeakMarketCap:best?.peakMarketCap??null,bestTokenAddress:best?.tokenAddress??null,hitRate100k,hitRate1m:rate(winners1m,usable.length),recent5Hits100k:recent.filter(x=>x.crossed100k===true).length,recent5Hits1m:recent.filter(x=>x.crossed1m===true).length,recent5HitRate100k:recent.length===5?rate(recent.filter(x=>x.crossed100k===true).length,5):null,severeCrashCount,severeCrashRate,catastrophicCrashCount,catastrophicCrashRate:rate(catastrophicCrashCount,usable.length),firstLaunch:chronological[0]?.launchedAt??null,latestLaunch:chronological.at(-1)?.launchedAt??null,lastSuccessfulTokenAddress:lastSuccess?.tokenAddress??null,lastSuccessfulPeakMarketCap:lastSuccess?.peakMarketCap??null,sampleConfidence:usable.length>=10?'HIGH':usable.length>=5?'MEDIUM':usable.length>=2?'LOW':'INSUFFICIENT',tier,riskTier,isBlocked:riskTier!==null,blockReason:riskTier==='SCAMMER'?'verified repeated failed launches':riskTier==='SPAM_LAUNCHER'?'high-volume launcher with no verified $100K winner':riskTier==='HIGH_RISK'?'crash-heavy verified launch history':null,outcomes:chronological} satisfies PonsDeveloperIntelligence});const order:Record<PonsDeveloperTier,number>={LEGEND:0,KING:1,GEM:2,PROVEN:3,PROMISING:4,UNKNOWN:5,HIGH_RISK:6,SPAM_LAUNCHER:7,SCAMMER:8};return result.sort((a,b)=>order[a.tier]-order[b.tier]||b.launchesWithUsableOutcomes-a.launchesWithUsableOutcomes||a.developerAddress.localeCompare(b.developerAddress));
}
export async function buildPonsDeveloperIntelligence(source:PonsOutcomeDataSource,deployer?:string){const launches=await source.loadPonsLaunches(deployer?lower(deployer):undefined),tokens=[...new Set(launches.map(x=>lower(x.token_address)))],[creator,native]=await Promise.all([source.loadCreatorOutcomes(tokens),source.loadPonsNativeOutcomes?.(tokens)??Promise.resolve([])]);return aggregatePonsDeveloperIntelligence(bridgePonsTokenOutcomes(launches,creator,native));}
async function source():Promise<PonsOutcomeDataSource>{const{supabase}=await import('../../services/supabase.js');return{async loadPonsLaunches(deployer){const rows:PonsLaunchCensusRow[]=[];for(let from=0;;from+=1000){let q=supabase.from('pons_launches').select('token_address,deployer_address,protocol_version,block_timestamp').eq('chain','robinhood').order('block_timestamp').range(from,from+999);if(deployer)q=q.eq('deployer_address',deployer);const{data,error}=await q;if(error)throw new Error(`Pons launch load failed: ${error.message}`);rows.push(...((data??[]) as PonsLaunchCensusRow[]));if((data?.length??0)<1000)break}return rows},async loadCreatorOutcomes(tokens){const rows:ExistingCreatorOutcomeRow[]=[];for(let i=0;i<tokens.length;i+=200){const{data,error}=await supabase.from('creator_launches').select('token,creator_wallet,peak_market_cap,current_market_cap,crossed_100k,crossed_500k,crossed_1m,severe_crash,catastrophic_crash,tracking_complete,last_checked_at').eq('chain','robinhood').in('token',tokens.slice(i,i+200));if(error)throw new Error(`Exact-token outcome load failed: ${error.message}`);rows.push(...((data??[]) as ExistingCreatorOutcomeRow[]))}return rows},async loadPonsNativeOutcomes(tokens){const rows:PonsNativeOutcomeRow[]=[];for(let i=0;i<tokens.length;i+=200){const{data,error}=await supabase.from('pons_token_outcomes').select('token_address,peak_market_cap,current_market_cap,crossed_100k,crossed_500k,crossed_1m,crossed_5m,crossed_10m,severe_crash,catastrophic_crash,data_confidence,last_checked_at').eq('chain','robinhood').in('token_address',tokens.slice(i,i+200));if(error)throw new Error(`Pons-native outcome load failed: ${error.message}`);rows.push(...((data??[]) as PonsNativeOutcomeRow[]))}return rows}}}
export async function getPonsDeveloperIntelligence(deployer:string){return(await buildPonsDeveloperIntelligence(await source(),deployer))[0]??null}export async function getAllPonsDeveloperIntelligence(){return buildPonsDeveloperIntelligence(await source())}
