"use client";
import Link from "next/link";
import {useCallback,useEffect,useMemo,useState} from "react";
import type {ApiResponse,Chain,LiveOpportunity,OpportunitiesResponse} from "@/lib/dashboard/types";
type ChainFilter="all"|"solana"|"robinhood";
function money(v:number|null){return v===null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(v)}
function pct(v:number|null){return v===null?"—":`${v>=0?"+":""}${v.toFixed(1)}%`}
function relative(v:string){const ms=Date.now()-new Date(v).getTime();if(!Number.isFinite(ms)||ms<60000)return"now";const m=Math.floor(ms/60000);if(m<60)return`${m}m`;const h=Math.floor(m/60);return h<24?`${h}h`:`${Math.floor(h/24)}d`}
function meta(c:Chain){if(c==="robinhood")return{label:"ROBINHOOD · PONS",pill:"border-emerald-400/20 text-emerald-300"};if(c==="solana")return{label:"SOLANA",pill:"border-violet-400/20 text-violet-300"};return{label:c.toUpperCase(),pill:"border-white/10 text-zinc-400"}}
function stage(o:LiveOpportunity){if(o.status==="APPROVED"||o.status==="EXECUTED")return"ENTRY READY";if(o.status==="NEW")return"NEW SIGNAL";return"WATCHING"}
function url(o:LiveOpportunity){const p=new URLSearchParams({chain:o.chain,symbol:o.symbol,source:o.sourceAgent||"AlphaOS",confidence:String(o.confidence),risk:o.riskLevel});if(o.marketCap!==null)p.set("marketCap",String(o.marketCap));if(o.liquidity!==null)p.set("liquidity",String(o.liquidity));return `/intelligence/${encodeURIComponent(o.token)}?${p}`}
function Card({o}:{o:LiveOpportunity}){const m=meta(o.chain);const from=o.marketCap&&o.athMarketCap&&o.athMarketCap>0?(o.marketCap/o.athMarketCap-1)*100:null;return <article className="rounded-2xl border border-white/[0.08] bg-[#181d21] p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><span className={`rounded-full border bg-white/[0.03] px-2.5 py-1 text-[9px] font-semibold tracking-[0.12em] ${m.pill}`}>{m.label}</span><div className="mt-3 flex items-center gap-2"><h3 className="text-2xl font-semibold">{o.symbol}</h3><span className="rounded-full border border-white/[0.08] px-2 py-0.5 text-[8px] font-semibold text-zinc-400">{stage(o)}</span></div></div><div className="text-right"><p className="text-3xl font-semibold text-emerald-300">{o.confidence}</p><p className="text-[8px] text-zinc-600">ALPHA</p></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-xl bg-white/[0.025] p-2.5"><p className="text-[8px] text-zinc-600">MARKET CAP</p><p className="mt-1 text-sm font-medium">{money(o.marketCap)}</p></div><div className="rounded-xl bg-amber-300/[0.035] p-2.5"><p className="text-[8px] text-zinc-600">RECORDED ATH</p><p className="mt-1 text-sm font-semibold text-amber-200">{money(o.athMarketCap)}</p>{from!==null?<p className="text-[8px] text-zinc-600">{pct(from)} now</p>:null}</div><div className="rounded-xl bg-white/[0.025] p-2.5"><p className="text-[8px] text-zinc-600">LIQUIDITY</p><p className="mt-1 text-sm font-medium">{money(o.liquidity)}</p></div><div className="rounded-xl bg-white/[0.025] p-2.5"><p className="text-[8px] text-zinc-600">RISK</p><p className={`mt-1 text-sm font-medium ${o.riskLevel==="LOW"?"text-emerald-300":o.riskLevel==="HIGH"?"text-rose-300":"text-amber-300"}`}>{o.riskLevel}</p></div></div><div className="mt-4 flex items-center justify-between gap-3"><div><p className="text-[10px] text-zinc-500">{o.chain==="robinhood"?"PONS market intelligence":o.sourceAgent}</p><p className="mt-0.5 text-[9px] text-zinc-700">updated {relative(o.createdAt)} ago</p></div><Link href={url(o)} className="inline-flex min-h-10 items-center justify-center rounded-xl border border-emerald-300/25 bg-emerald-300/[0.08] px-4 text-xs font-semibold text-emerald-200">Open Intelligence →</Link></div></article>}
export default function LiveOpportunities(){const[data,setData]=useState<OpportunitiesResponse|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState<string|null>(null),[filter,setFilter]=useState<ChainFilter>("all");const load=useCallback(async(bg=false)=>{try{bg?setRefreshing(true):setLoading(true);setError(null);const r=await fetch("/api/opportunities",{cache:"no-store"}),p=await r.json() as ApiResponse<OpportunitiesResponse>;if(!r.ok||!p.success)throw new Error(p.success?"Unable to load Radar":p.error);setData(p.data)}catch(e){setError(e instanceof Error?e.message:"Unable to load Radar")}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load();const t=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(t)},[load]);const items=useMemo(()=>data?.items.filter(i=>filter==="all"||i.chain===filter)??[],[data,filter]);const ready=data?.items.filter(i=>stage(i)==="ENTRY READY").length??0,watching=data?.items.filter(i=>stage(i)==="WATCHING").length??0;return <section className="mt-5"><div className="grid grid-cols-2 gap-3 sm:max-w-md"><div className="rounded-2xl border border-emerald-400/15 bg-emerald-400/[0.05] p-4"><p className="text-2xl font-semibold">{ready}</p><p className="mt-1 text-[9px] text-emerald-300">ENTRY READY</p></div><div className="rounded-2xl border border-white/[0.08] bg-white/[0.02] p-4"><p className="text-2xl font-semibold">{watching}</p><p className="mt-1 text-[9px] text-zinc-600">WATCHING</p></div></div><div className="mt-5 flex items-center justify-between gap-3"><div className="flex rounded-xl border border-white/[0.08] bg-white/[0.02] p-1">{(["all","solana","robinhood"] as ChainFilter[]).map(v=><button key={v} onClick={()=>setFilter(v)} className={`rounded-lg px-3 py-2 text-[10px] font-semibold uppercase ${filter===v?"bg-white/[0.08] text-white":"text-zinc-600"}`}>{v==="all"?"All":v==="robinhood"?"Robinhood · PONS":"Solana"}</button>)}</div><button onClick={()=>void load(true)} disabled={refreshing} className="text-xs text-zinc-600">{refreshing?"Refreshing…":"Refresh"}</button></div>{loading&&!data?<div className="mt-5 h-64 animate-pulse rounded-2xl border border-white/[0.08] bg-white/[0.02]"/>:null}{error&&!data?<div className="mt-5 rounded-2xl border border-rose-400/20 p-5 text-sm text-rose-300">{error}</div>:null}{data&&items.length===0?<div className="mt-5 rounded-2xl border border-dashed border-white/[0.08] p-10 text-center text-sm text-zinc-600">No active opportunities on this chain right now. AlphaOS is still scanning.</div>:null}{items.length?<div className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(i=><Card key={String(i.id)} o={i}/>)}</div>:null}{error&&data?<p className="mt-3 text-xs text-amber-300">Refresh failed; showing the last successful Radar snapshot.</p>:null}</section>}
