create table if not exists public.pons_launches (
  id bigint generated by default as identity primary key,
  chain text not null, protocol text not null, protocol_version text not null,
  factory_address text not null, token_address text not null, deployer_address text not null,
  curve_address text, pool_address text, pair_token_address text,
  launch_config_id numeric(78,0), graduation_threshold numeric(78,0), initial_buy_amount numeric(78,0),
  block_number bigint not null, block_timestamp timestamptz not null,
  transaction_hash text not null, log_index integer not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint pons_launches_event_unique unique (chain, factory_address, transaction_hash, log_index),
  constraint pons_launches_addresses_lowercase check (
    factory_address = lower(factory_address) and token_address = lower(token_address) and deployer_address = lower(deployer_address)
    and (curve_address is null or curve_address = lower(curve_address)) and (pool_address is null or pool_address = lower(pool_address))
    and (pair_token_address is null or pair_token_address = lower(pair_token_address))),
  constraint pons_launches_block_nonnegative check (block_number >= 0),
  constraint pons_launches_log_index_nonnegative check (log_index >= 0)
);
create index if not exists pons_launches_deployer_time_idx on public.pons_launches(chain, deployer_address, block_timestamp);
create index if not exists pons_launches_token_factory_idx on public.pons_launches(chain, token_address, factory_address);
alter table public.pons_launches enable row level security;
comment on table public.pons_launches is 'Authoritative read-only Pons launch census; no quality or market-performance inference.';

create table if not exists public.pons_indexer_checkpoints (
  chain text not null, protocol text not null, factory_id text not null, factory_address text not null,
  last_processed_block bigint not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  primary key (chain, factory_id),
  constraint pons_indexer_checkpoint_block_nonnegative check (last_processed_block >= 0),
  constraint pons_indexer_checkpoint_address_lowercase check (factory_address = lower(factory_address))
);
alter table public.pons_indexer_checkpoints enable row level security;
comment on table public.pons_indexer_checkpoints is 'Restart-safe per-deployment checkpoint for the Pons historical census.';
