create table if not exists public.pons_token_outcomes (
  id bigint generated by default as identity primary key,
  chain text not null default 'robinhood', factory_address text not null, protocol_version text not null,
  token_address text not null, deployer_address text not null, launched_at timestamptz not null,
  first_market_cap numeric, current_market_cap numeric, peak_market_cap numeric,
  crossed_100k boolean, crossed_500k boolean, crossed_1m boolean, crossed_5m boolean, crossed_10m boolean,
  severe_crash boolean, catastrophic_crash boolean, observation_count integer not null default 0,
  data_confidence text not null, first_observed_at timestamptz, last_observed_at timestamptz,
  peak_source text, current_source text, last_checked_at timestamptz not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (chain, factory_address, token_address),
  check (factory_address = lower(factory_address) and token_address = lower(token_address) and deployer_address = lower(deployer_address)),
  check (observation_count >= 0), check (data_confidence in ('VERIFIED_HISTORY','CURRENT_ONLY','UNKNOWN'))
);
create index if not exists pons_token_outcomes_deployer_idx on public.pons_token_outcomes(chain, deployer_address, launched_at desc);
create index if not exists pons_token_outcomes_tier_evidence_idx on public.pons_token_outcomes(chain, peak_market_cap desc) where peak_market_cap is not null;
alter table public.pons_token_outcomes enable row level security;

create or replace function public.preserve_pons_verified_peak() returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if old.data_confidence = 'VERIFIED_HISTORY' and (new.peak_market_cap is null or new.peak_market_cap < old.peak_market_cap) then
    new.peak_market_cap := old.peak_market_cap; new.peak_source := old.peak_source;
  end if;
  if old.data_confidence = 'VERIFIED_HISTORY' then
    new.data_confidence := old.data_confidence;
  end if;
  new.crossed_100k := coalesce(old.crossed_100k, false) or coalesce(new.crossed_100k, false);
  new.crossed_500k := coalesce(old.crossed_500k, false) or coalesce(new.crossed_500k, false);
  new.crossed_1m := coalesce(old.crossed_1m, false) or coalesce(new.crossed_1m, false);
  new.crossed_5m := coalesce(old.crossed_5m, false) or coalesce(new.crossed_5m, false);
  new.crossed_10m := coalesce(old.crossed_10m, false) or coalesce(new.crossed_10m, false);
  new.observation_count := greatest(old.observation_count, new.observation_count);
  new.updated_at := now(); return new;
end $$;
revoke execute on function public.preserve_pons_verified_peak() from public, anon, authenticated;
create trigger preserve_pons_verified_peak_before_update before update on public.pons_token_outcomes
for each row execute function public.preserve_pons_verified_peak();

create table if not exists public.pons_developer_registry (
  chain text not null default 'robinhood', deployer_address text not null,
  total_launches integer not null, usable_outcomes integer not null,
  winners_100k integer not null, winners_500k integer not null, winners_1m integer not null,
  winners_5m integer not null, winners_10m integer not null, best_verified_peak_market_cap numeric,
  hit_rate_100k numeric, hit_rate_1m numeric, recent_5_hits_100k integer, recent_5_hits_1m integer,
  severe_crash_count integer not null, severe_crash_rate numeric,
  catastrophic_crash_count integer not null, catastrophic_crash_rate numeric,
  first_launch_at timestamptz, latest_launch_at timestamptz, best_token_address text,
  last_successful_token_address text, last_successful_peak_market_cap numeric,
  confidence text not null, tier text not null, risk_tier text,
  is_blocked boolean not null default false, block_reason text, blocked_at timestamptz,
  refreshed_at timestamptz not null default now(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  primary key (chain, deployer_address), check (deployer_address = lower(deployer_address)),
  check (tier in ('LEGEND','KING','GEM','PROVEN','PROMISING','UNKNOWN','HIGH_RISK','SPAM_LAUNCHER','SCAMMER')),
  check (risk_tier is null or risk_tier in ('HIGH_RISK','SPAM_LAUNCHER','SCAMMER')),
  check (confidence in ('HIGH','MEDIUM','LOW','INSUFFICIENT'))
);
create index if not exists pons_developer_registry_tier_idx on public.pons_developer_registry(chain, tier, best_verified_peak_market_cap desc);
create index if not exists pons_developer_registry_blocked_idx on public.pons_developer_registry(chain, is_blocked) where is_blocked;
alter table public.pons_developer_registry enable row level security;
comment on table public.pons_token_outcomes is 'Derived exact-token Pons outcome evidence; pons_launches remains authoritative.';
comment on table public.pons_developer_registry is 'Derived Pons developer intelligence and durable block evidence; never replaces census history.';
