-- Backend-only objects: service_role access preserved; browser roles denied.
SET lock_timeout = '5s';
ALTER TABLE public.admin_trades ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.admin_trades FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.admin_trades TO service_role;
ALTER TABLE public.alert_deliveries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.alert_deliveries FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.alert_deliveries TO service_role;
ALTER TABLE public.alpha_alert_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.alpha_alert_events FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.alpha_alert_events TO service_role;
ALTER TABLE public.alpha_alert_outcomes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.alpha_alert_outcomes FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.alpha_alert_outcomes TO service_role;
ALTER TABLE public.alpha_winner_feature_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.alpha_winner_feature_snapshots FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.alpha_winner_feature_snapshots TO service_role;
ALTER TABLE public.dev_tokens ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.dev_tokens FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.dev_tokens TO service_role;
ALTER TABLE public.devs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.devs FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.devs TO service_role;
ALTER TABLE public.learning_recommendations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.learning_recommendations FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.learning_recommendations TO service_role;
ALTER TABLE public.opportunity_deliveries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.opportunity_deliveries FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.opportunity_deliveries TO service_role;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.payments FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.payments TO service_role;
ALTER TABLE public.robinhood_dex_paid_security_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.robinhood_dex_paid_security_snapshots FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.robinhood_dex_paid_security_snapshots TO service_role;
ALTER TABLE public.shadow_decision_outcomes ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.shadow_decision_outcomes FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.shadow_decision_outcomes TO service_role;
ALTER TABLE public.shadow_intelligence_decisions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.shadow_intelligence_decisions FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.shadow_intelligence_decisions TO service_role;
ALTER TABLE public.user_opportunity_watchlist ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.user_opportunity_watchlist FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.user_opportunity_watchlist TO service_role;
ALTER TABLE public.user_paper_sniper_configs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.user_paper_sniper_configs FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.user_paper_sniper_configs TO service_role;
ALTER TABLE public.user_tracked_wallets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.user_tracked_wallets FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.user_tracked_wallets TO service_role;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.users FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.users TO service_role;
ALTER TABLE public.wallet_activity_deliveries ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.wallet_activity_deliveries FROM anon, authenticated, PUBLIC;
GRANT ALL ON public.wallet_activity_deliveries TO service_role;
ALTER VIEW public.alpha_live_asset_state_24h SET (security_invoker = true);
REVOKE ALL ON public.alpha_live_asset_state_24h FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.alpha_live_asset_state_24h TO service_role;
ALTER VIEW public.latest_token_intelligence SET (security_invoker = true);
REVOKE ALL ON public.latest_token_intelligence FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.latest_token_intelligence TO service_role;
ALTER VIEW public.pending_payments SET (security_invoker = true);
REVOKE ALL ON public.pending_payments FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.pending_payments TO service_role;
ALTER VIEW public.token_event_timeline SET (security_invoker = true);
REVOKE ALL ON public.token_event_timeline FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.token_event_timeline TO service_role;
ALTER VIEW public.user_counts SET (security_invoker = true);
REVOKE ALL ON public.user_counts FROM anon, authenticated, PUBLIC;
GRANT SELECT ON public.user_counts TO service_role;
ALTER FUNCTION public.set_updated_at() SET search_path = public, pg_temp;
ALTER FUNCTION public.expire_due_subscriptions() SET search_path = public, pg_temp;
ALTER FUNCTION public.set_trade_position_updated_at() SET search_path = public, pg_temp;
ALTER FUNCTION public.alphaos_touch_updated_at() SET search_path = public, pg_temp;
ALTER FUNCTION public.reject_alpha_alert_event_mutation() SET search_path = public, pg_temp;
ALTER FUNCTION public.pons_preserve_verified_peak() SET search_path = public, pg_temp;
ALTER FUNCTION public.derive_existing_token_monitor_scores() SET search_path = public, pg_temp;
ALTER FUNCTION public.enrich_pons_creator_launch_count() SET search_path = public, pg_temp;
REVOKE EXECUTE ON FUNCTION public.select_alpha_outcome_candidates(timestamptz,timestamptz,timestamptz,integer) FROM anon, authenticated, PUBLIC;
GRANT EXECUTE ON FUNCTION public.select_alpha_outcome_candidates(timestamptz,timestamptz,timestamptz,integer) TO service_role;

