import Link from "next/link";
import AppShell from "@/components/layout/AppShell";
const features = [
 ["Boost", "A new observed boost or boost increment.", "Promotion activity. Inspect liquidity, valuation and ownership before acting."],
 ["DEX Paid", "A confirmed supported DEX visibility payment.", "A distinct promotion event; payment is not proof of trading quality."],
 ["Social Mafia", "Qualifying launchpad and authoritative exact-contract social evidence.", "Social verification can remain unavailable when X content cannot be read."],
 ["Protocol watch", "A qualifying project describing itself as a protocol, with required social links.", "Exploratory category. A protocol label and social links do not establish legitimacy."],
 ["Trade Setup Watch", "Qualifying recovery evidence or complete-history volume confirmation.", "A watch condition, not a buy instruction. Missing history cannot qualify a volume signal."],
 ["Creator & Supply Journey", "Requested research or supported observed wallet activity.", "Shows available holdings and transfers. A transfer alone does not prove a sale or wallet ownership."],
];
export default async function GuidePage({ searchParams }: { searchParams: Promise<{ bot?: string }> }) { const { bot } = await searchParams; return <AppShell><main className="premium-page"><div className="premium-container"><p className="premium-eyebrow">THE ALPHAOS FIELD GUIDE</p><h1 className="page-title">Know what each alert means.</h1><p className="page-intro">An alert explains an observed event. Your decision still depends on the current market and the evidence that is available.</p>{bot === "unavailable" && <p role="status" className="data-notice">The Telegram link could not be resolved right now. Open your existing AlphaOS chat in Telegram; do not share your bot token.</p>}<section className="info-panel"><h2>Telegram commands</h2><div className="command-grid"><p><code>/start</code><span>Open the bot and its feature menu.</span></p><p><code>/scan CONTRACT</code><span>Research a supported token.</span></p><p><code>/scan WALLET</code><span>Research a creator or wallet.</span></p><p><code>/scan_on</code><span>Enable supported group scanning as a group administrator.</span></p></div><p>Add the bot to your group, then enable scanning. If plain addresses are not visible to the bot because of group privacy, use <code>/scan@BotUsername CONTRACT</code> with the bot&apos;s actual username. Private alert preferences are managed separately in the bot.</p><a href="/api/open-bot" className="alpha-button-primary mt-4">Open Telegram ↗</a></section><div className="feature-grid">{features.map(([title, trigger, meaning]) => <section className="feature-card" key={title}><h2>{title}</h2><p><strong>When it appears:</strong> {trigger}</p><p>{meaning}</p></section>)}</div><section className="info-panel"><h2>Read the card in this order</h2><ol><li>Why alerted: identify the actual event.</li><li>Market cap, price, liquidity and volume: check source and observation time.</li><li>Dev holding and Top 10: inspect concentration where coverage exists.</li><li>Risk: distinguish verified origin from independently checked sellability.</li><li>Open the correct venue and validate current conditions.</li></ol><p>ARC Boost and DEX Paid are event notifications; liquidity and sellability may be unchecked. Verified launchpad origin is not a guarantee against market losses.</p><Link href="/status" className="text-link">Understand data coverage →</Link></section></div></main></AppShell>; }
